### ISSUE TITLE
Kernel died, restarting

### ISSUE THREAD

**Issue by 0x06i** [Andrew-AbiMansour/PyGran#3]
Hello,

I installed and tested successfully according to the instructions and test here.
(https://andrew-abimansour.github.io/PyGran/docs/introduction.html#installation)

When I try to run a simple code on spyder, on line "sim = simulation.DEM(**param)", I get "Kernel died, restarting" message.

The screenshot is below.

I need help to proceed.

Thank you.

![Screenshot from 2019-12-20 08-05-38](https://user-images.githubusercontent.com/12110917/71231589-af396300-22ff-11ea-87a7-7fdddd8cd75b.png)

**Comment by anabiman** [comment]
Can you please attach the pygran log file as well? Running pygran from the terminal would yield a lot more useful info for debugging.

**Comment by 0x06i** [comment]
Thank you. Yes, the terminal provided more information.

My mesh file was at the wrong path. I fixed it.

Now, the error in Spyder is the same: "Kernel died, restarting".

The error in terminal is as follows:
Reading STL file '/home/ilhan/LIGGGHTS-PUBLIC/src/mesh/square.stl' (mesh processing step 1/3) 
ERROR: Unbalanced quotes in input line (../input.cpp:416)

The screenshot and the log file is attached.

[pygran.log](https://github.com/Andrew-AbiMansour/PyGran/files/3992199/pygran.log)
![Screenshot from 2019-12-22 09-40-43](https://user-images.githubusercontent.com/12110917/71318288-01b18580-24a0-11ea-8c7e-8c02b0247ed5.png)

I am also new to LIGGGHTS. So, any guidance is very precious. Thank you.

**Comment by 0x06i** [comment]
I have also tried with different examples and different stl files. The result is the same.

**Comment by anabiman** [comment]
Are you generating your own STL files? Plz attach the liggghts.log file as well.

**Comment by 0x06i** [comment]
I have been trying only with the following examples and stl files: http://andrew-abimansour.github.io/PyGran/tests/examples.html

square.stl mentioned above is the one here: https://github.com/Andrew-AbiMansour/PyGran/tree/master/tests/scripts/DEM/compaction/mesh

Log files of yesterday's test:
[liggghts.log](https://github.com/Andrew-AbiMansour/PyGran/files/3997346/liggghts.log)
[pygran.log](https://github.com/Andrew-AbiMansour/PyGran/files/3997349/pygran.log)

**Comment by anabiman** [comment]
I can reproduce the compaction example using python v3.7.3 and PyGran v1.2.1. If you're using the latest version of PyGran then 

`import PyGran._version`
`PyGran._version.__version__`

should return '1.2.1' Can you verify this is true?

**Comment by 0x06i** [comment]
Yes, it returns '1.2.1'. 

![Screenshot from 2019-12-25 13-45-05](https://user-images.githubusercontent.com/12110917/71443602-ed2df100-271c-11ea-84b0-9788ae3316d8.png)

**Comment by 0x06i** [comment]
I have skipped PyGran for now and tried to test LIGGGHTS directly from the PyGran folder. A new installation was required. I installed to the same folder.
I am now able to run the chute wear example completely and the error with the PyGran is the same after the new installation. Weird. Screenshot:

![Screenshot from 2019-12-25 16-37-12](https://user-images.githubusercontent.com/12110917/71446520-40ac3900-2735-11ea-8c5a-e941420e27ee.png)

**Comment by 0x06i** [comment]
If you'd like to check by yourself, I can arrange a remote connection software. Please suggest a non-public contact info to pass the login information if you consider.

**Comment by 0x06i** [comment]
Hello, the issue is resolved. It is somehow my mistake, sorry.

More detail:
I had downloaded the square.stl as follows via the browser. I realized that it is saving the html page as the stl file...

![Screenshot from 2019-12-26 10-50-25](https://user-images.githubusercontent.com/12110917/71465483-d4314880-27cd-11ea-9031-58f1606db13b.png)

**Comment by anabiman** [comment]
Thanks for the info. I will fix the typo on the website too. In the future, if you need to reach me via email, plz use PyGran [at] support [dot] org.
