### ISSUE TITLE
Quotes missing at compaction example web page

### ISSUE THREAD

**Issue by 0x06i** [Andrew-AbiMansour/PyGran#4]
Not an important issue indeed but the quotes for quotes for 'wallZ' are missing in the following lines.

No problem in the py file. Only at the web page.

Relax the system (move wall upwards)
moveZ = sim.moveMesh(name=wallZ, linear=(0, 0, 0.01))

http://andrew-abimansour.github.io/PyGran/tests/scripts/DEM/compaction/compaction.html

**Comment by anabiman** [comment]
Fixed in v1.2.2.
Thank you for your help.
