### ISSUE TITLE
ModuleNotFoundError: No module named 'pygran_sim'

### ISSUE THREAD

**Issue by pavlo-kashko** [Andrew-AbiMansour/PyGran#6]
I was trying to install PyGran on my laptop following the instructions (Installation example: ubuntu 18.04) from here: 
http://andrew-abimansour.github.io/PyGran/docs/introduction.html.
However, on the very last step while making pytest to check if everything was installed properly, next error happened:

  pytest -v pygran/tests/test_sim

======================================== test session starts ========================================
platform linux -- Python 3.8.10, pytest-7.1.2, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/pavel/Desktop/PyGran
plugins: cov-3.0.0
collected 0 items / 1 error                                                                         

============================================== ERRORS ===============================================
______________________ ERROR collecting pygran/tests/test_sim/test_sim_flow.py ______________________
ImportError while importing test module '/home/pavel/Desktop/PyGran/pygran/tests/test_sim/test_sim_flow.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
pygran/tests/test_sim/test_sim_flow.py:1: in <module>
    from pygran import simulation
../../.local/lib/python3.8/site-packages/pygran/__init__.py:32: in <module>
    from pygran_sim.tools import configure
E   ModuleNotFoundError: No module named 'pygran_sim'
========================================= warnings summary ==========================================
../../.local/lib/python3.8/site-packages/pygran/analysis.py:35
  /home/pavel/.local/lib/python3.8/site-packages/pygran/analysis.py:35: UserWarning: pygran_analysis uninstalled. Solve by: pip install pygran_analysis.
    warnings.warn("pygran_analysis uninstalled. Solve by: pip install pygran_analysis.")

../../.local/lib/python3.8/site-packages/pygran/params.py:35
  /home/pavel/.local/lib/python3.8/site-packages/pygran/params.py:35: UserWarning: pygran_params uninstalled. Solve by: pip install pygran_params.
    warnings.warn("pygran_params uninstalled. Solve by: pip install pygran_params.")

../../.local/lib/python3.8/site-packages/pygran/simulation.py:35
  /home/pavel/.local/lib/python3.8/site-packages/pygran/simulation.py:35: UserWarning: pygran_simulation uninstalled. Solve by: pip install pygran_simulation.
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
====================================== short test summary info ======================================
ERROR pygran/tests/test_sim/test_sim_flow.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=================================== 3 warnings, 1 error in 0.07s ====================================

**Environment:**
 - OS: Ubuntu 20.04 LTS
 - PyGran version: 1.3.1
 - CPython version: 3.8.10

I would be very thankful for any help with this issue!

**Comment by anabiman** [comment]
Thanks for reporting this @PawaKawko . Currently the master branch is being refactored. I suggest you use v1.3.1 instead.

**Comment by anabiman** [comment]
@PawaKawko version `1.4.0` has been released. Installing pygran should now automatically include installation of `pygran_sim`.
